### ISSUE TITLE
failed calling webhook "prometheusrulemutate.monitoring.coreos.com"

### ISSUE THREAD

**Issue by david-freistrom** [enix/helm-charts#58] opened 2021-03-26 03:05 UTC
I tried to install your Helm chart into my on-prem kubernetes cluster by
 ```bash
$ helm -n monitoring install x509-certificate-exporter enix/x509-certificate-exporter -f ./x509-exporter.values.yml
```

The values.yml is still the default from your git repo.

My enabled admission plugins are 
- NodeRestriction
- NamespaceLifecycle
- LimitRanger
- ServiceAccount
- DefaultStorageClass
- DefaultTolerationSeconds
- MutatingAdmissionWebhook
- ValidatingAdmissionWebhook
- Priority
- ResourceQuota
- PodSecurityPolicy

I installed also a webhook:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: prometheus-operator-rulesvalidation
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJjekNDQVJtZ0F3SUJBZ0lRZEtYaWh3Yk53UWpXWXdFVTJ6d3hvakFLQmdncWhrak9QUVFEQWpBT01Rd3cKQ2dZRFZRUUtFd051YVd3d0lCY05NakV3TXpJMU1ERXhOVEU0V2hnUE1qRXlNVEF6TURFd01URTFNVGhhTUE0eApEREFLQmdOV>
      service:
        name: prometheus-kube-prometheus-operator
        namespace: monitoring
        path: /admission-prometheusrules/mutate
    failurePolicy: Fail
    name: prometheusrulemutate.monitoring.coreos.com
    namespaceSelector: {}
    rules:
      - apiGroups:
          - monitoring.coreos.com
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - prometheusrules
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
```

But I get all the time the follwoing error:

```bash
$ helm -n monitoring upgrade -i x509-certificate-exporter enix/x509-certificate-exporter -f ./x509-exporter.values.yml 
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://prometheus-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s": dial tcp 172.20.151.210:443: i/o timeout
```

The Service as well as the Pod for prometheus operator is installed, working and reachable inside monitoring namespace at 172.20.151.210:443.

**Comment by npdgm** [comment] 2021-04-28 11:48
Hi @david-freistrom
Sorry it took so long to reply, we didn't notice the issue.
However the error you encountered goes beyond the scope of deploying and running the exporter. This seems to be a CNI or service mesh issue, and perhaps specific to a cloud provider or k8s distribution.
Since the time it was reported I hope you worked around it or found the root cause.
I'll be closing the issue now, as the PrometheusRule resource is optional and no improvement is identified. The [Kubernetes Slack](https://slack.k8s.io/) and the [Prometheus Community](https://prometheus.io/community/) are good places to reach out for help.
But if you believe that PrometheusRule is incorrect then feel free to reopen with your findings.
Cheers

**Closed by npdgm** 2021-04-28 11:48 UTC
Labels: x509-certificate-exporter
